version: 3

tasks:
  setup:
    cmds:
      - go install github.com/deepmap/oapi-codegen/v2/cmd/oapi-codegen@v2.1.0

  build:
    sources:
      - ./**/*.go
    generates:
      - ./platform-demo
    cmds:
      - go build

  generate:
    cmds:
      - go generate ./...
